from pathlib import Path


def replace_once(path: str, old: str, new: str):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'bloco nao encontrado em {path}: {old[:220]!r}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')

build = 'app/build.gradle.kts'
replace_once(build, 'versionCode = 1000145', 'versionCode = 1000146')

recorder = 'app/src/main/java/com/steadyvault/camera/capture/recorder/DirectMediaRecorderBackend.kt'
replace_once(recorder, '''    private val targetFps: Int,\n    private val videoMime: String,''', '''    private val targetFps: Int,\n    private val highSpeedCapture: Boolean,\n    private val videoMime: String,''')
replace_once(recorder, '''                setVideoSize(width, height)\n                setVideoFrameRate(targetFps)\n                setVideoEncodingBitRate(videoBitrate)''', '''                setVideoSize(width, height)\n                // Constrained high-speed tem uma taxa de captura propria. Informar a\n                // mesma taxa ao MediaRecorder evita tratar os bursts como stream comum.\n                if (highSpeedCapture) setCaptureRate(targetFps.toDouble())\n                setVideoFrameRate(targetFps)\n                setVideoEncodingBitRate(videoBitrate)''')

service = 'app/src/main/java/com/steadyvault/camera/capture/service/CaptureService.kt'
replace_once(service, '''            targetFps = cameraProfile.targetFps,\n            videoMime = encoderProfile.mime,''', '''            targetFps = cameraProfile.targetFps,\n            highSpeedCapture = cameraProfile.highSpeed,\n            videoMime = encoderProfile.mime,''')

validator = Path('app/src/main/java/com/steadyvault/camera/capture/timing/HighFpsCadenceValidator.kt')
validator.parent.mkdir(parents=True, exist_ok=True)
validator.write_text(r'''package com.steadyvault.camera.capture.timing

import android.media.MediaExtractor
import android.media.MediaFormat
import java.io.File
import java.util.Locale

object HighFpsCadenceValidator {
    data class Result(
        val samples: Int,
        val actualFps: Double,
        val largeGapRatio: Double,
        val shortBurstRatio: Double,
        val stable: Boolean
    ) {
        val label: String get() = String.format(Locale.getDefault(), "%.1f", actualFps)
    }

    fun inspect(file: File, targetFps: Int): Result? {
        if (!file.isFile || targetFps < 120) return null
        val extractor = MediaExtractor()
        return try {
            extractor.setDataSource(file.absolutePath)
            val videoTrack = (0 until extractor.trackCount).firstOrNull { index ->
                extractor.getTrackFormat(index).getString(MediaFormat.KEY_MIME)?.startsWith("video/") == true
            } ?: return null
            extractor.selectTrack(videoTrack)
            val pts = ArrayList<Long>(2048)
            while (extractor.sampleTrackIndex >= 0 && pts.size < MAX_SAMPLES) {
                extractor.sampleTime.takeIf { it >= 0L }?.let(pts::add)
                if (!extractor.advance()) break
            }
            if (pts.size < MIN_SAMPLES) return null
            pts.sort()
            val distinct = pts.distinct()
            if (distinct.size < MIN_SAMPLES) return null
            val spanUs = distinct.last() - distinct.first()
            if (spanUs < MIN_SPAN_US) return null
            val nominalUs = 1_000_000.0 / targetFps.toDouble()
            val deltas = distinct.zipWithNext { a, b -> (b - a).toDouble() }.filter { it > 0.0 }
            if (deltas.isEmpty()) return null
            val actualFps = (distinct.size - 1).toDouble() * 1_000_000.0 / spanUs.toDouble()
            val largeGapRatio = deltas.count { it > nominalUs * LARGE_GAP_FACTOR }.toDouble() / deltas.size
            val shortBurstRatio = deltas.count { it < nominalUs * SHORT_BURST_FACTOR }.toDouble() / deltas.size
            val fpsRatio = actualFps / targetFps.toDouble()
            val stable = fpsRatio in MIN_FPS_RATIO..MAX_FPS_RATIO &&
                largeGapRatio <= MAX_LARGE_GAP_RATIO && shortBurstRatio <= MAX_SHORT_BURST_RATIO
            Result(distinct.size, actualFps, largeGapRatio, shortBurstRatio, stable)
        } catch (_: Throwable) {
            null
        } finally {
            runCatching { extractor.release() }
        }
    }

    private const val MAX_SAMPLES = 6000
    private const val MIN_SAMPLES = 40
    private const val MIN_SPAN_US = 500_000L
    private const val LARGE_GAP_FACTOR = 1.75
    private const val SHORT_BURST_FACTOR = 0.65
    private const val MIN_FPS_RATIO = 0.88
    private const val MAX_FPS_RATIO = 1.12
    private const val MAX_LARGE_GAP_RATIO = 0.15
    private const val MAX_SHORT_BURST_RATIO = 0.30
}
''', encoding='utf-8')

state = 'app/src/main/java/com/steadyvault/camera/core/state/CaptureStateStore.kt'
replace_once(state, '''    private const val KEY_STARTED_AT_ELAPSED = "started_at_elapsed"''', '''    private const val KEY_STARTED_AT_ELAPSED = "started_at_elapsed"\n    private const val KEY_HISTORY_SCHEMA = "effective_history_schema"\n    private const val HISTORY_SCHEMA = 2''')
replace_once(state, '''    fun updateEffectiveMode(\n        context: Context,\n        resolutionValue: String,\n        resolutionLabel: String,\n        fps: Int\n    ) {\n        if (resolutionLabel.isBlank() || fps <= 0) return\n        val safeValue = resolutionValue.takeIf {\n            it in CaptureSettings.supportedResolutionValues\n        } ?: resolutionValueFromLabel(resolutionLabel)\n        preferences(context).edit()\n            .putString(KEY_EFFECTIVE_RESOLUTION_VALUE, safeValue)\n            .putString(KEY_EFFECTIVE_RESOLUTION, resolutionLabel)\n            .putInt(KEY_EFFECTIVE_FPS, fps)\n            .putString(historyResolutionValueKey(fps), safeValue)\n            .putString(historyResolutionLabelKey(fps), resolutionLabel)\n            .putLong(historyUpdatedKey(fps), System.currentTimeMillis())\n            .apply()\n    }''', '''    fun updateEffectiveMode(\n        context: Context,\n        resolutionValue: String,\n        resolutionLabel: String,\n        fps: Int,\n        rememberHistory: Boolean = true\n    ) {\n        if (resolutionLabel.isBlank() || fps <= 0) return\n        val safeValue = resolutionValue.takeIf { it in CaptureSettings.supportedResolutionValues }\n            ?: resolutionValueFromLabel(resolutionLabel)\n        preferences(context).edit()\n            .putString(KEY_EFFECTIVE_RESOLUTION_VALUE, safeValue)\n            .putString(KEY_EFFECTIVE_RESOLUTION, resolutionLabel)\n            .putInt(KEY_EFFECTIVE_FPS, fps)\n            .apply {\n                if (rememberHistory) {\n                    putString(historyResolutionValueKey(fps), safeValue)\n                    putString(historyResolutionLabelKey(fps), resolutionLabel)\n                    putLong(historyUpdatedKey(fps), System.currentTimeMillis())\n                }\n            }\n            .apply()\n    }\n\n    fun rememberValidatedModeForFps(context: Context, resolutionValue: String, resolutionLabel: String, fps: Int) {\n        if (fps <= 0 || resolutionLabel.isBlank()) return\n        val safeValue = resolutionValue.takeIf { it in CaptureSettings.supportedResolutionValues }\n            ?: resolutionValueFromLabel(resolutionLabel)\n        preferences(context).edit()\n            .putString(historyResolutionValueKey(fps), safeValue)\n            .putString(historyResolutionLabelKey(fps), resolutionLabel)\n            .putLong(historyUpdatedKey(fps), System.currentTimeMillis())\n            .apply()\n    }\n\n    fun clearEffectiveModeHistoryForFps(context: Context, fps: Int) {\n        preferences(context).edit()\n            .remove(historyResolutionValueKey(fps))\n            .remove(historyResolutionLabelKey(fps))\n            .remove(historyUpdatedKey(fps))\n            .apply()\n    }''')
replace_once(state, '''    fun effectiveModeForFps(context: Context, fps: Int): EffectiveMode? {\n        if (fps <= 0) return null\n        val preferences = preferences(context)''', '''    fun effectiveModeForFps(context: Context, fps: Int): EffectiveMode? {\n        if (fps <= 0) return null\n        migrateEffectiveHistoryIfNeeded(context)\n        val preferences = preferences(context)''')
replace_once(state, '''    private fun resolutionValueFromLabel(label: String): String = when {''', '''    private fun migrateEffectiveHistoryIfNeeded(context: Context) {\n        val prefs = preferences(context)\n        if (prefs.getInt(KEY_HISTORY_SCHEMA, 0) >= HISTORY_SCHEMA) return\n        prefs.edit()\n            .remove(historyResolutionValueKey(120))\n            .remove(historyResolutionLabelKey(120))\n            .remove(historyUpdatedKey(120))\n            .remove(historyResolutionValueKey(240))\n            .remove(historyResolutionLabelKey(240))\n            .remove(historyUpdatedKey(240))\n            .putInt(KEY_HISTORY_SCHEMA, HISTORY_SCHEMA)\n            .apply()\n    }\n\n    private fun resolutionValueFromLabel(label: String): String = when {''')

replace_once(service, '''import com.steadyvault.camera.capture.timing.SensorCadencePolicy''', '''import com.steadyvault.camera.capture.timing.SensorCadencePolicy\nimport com.steadyvault.camera.capture.timing.HighFpsCadenceValidator''')
replace_once(service, '''        CaptureStateStore.updateEffectiveMode(this, resolutionValue(profile.videoSize), sizeName(profile.videoSize), profile.targetFps)''', '''        CaptureStateStore.updateEffectiveMode(\n            this, resolutionValue(profile.videoSize), sizeName(profile.videoSize), profile.targetFps,\n            rememberHistory = profile.targetFps < CaptureModeStore.FPS_120\n        )''')
replace_once(service, '''        val qualityLabel = if (profile?.hdrHlg10 == true) "HDR HLG10" else "SDR BT.709"\n        // O original já está finalizado e indexado antes de entrar na fila. O reparo\n        // nunca recebe permissão para substituir este arquivo.\n        AutoGapRepairService.enqueue(this, finalFile, fps)\n        val message = "Vídeo salvo no cofre • ${sizeName(size)} • $fps FPS • $qualityLabel • ${formatDuration(durationSeconds)}"''', '''        val qualityLabel = if (profile?.hdrHlg10 == true) "HDR HLG10" else "SDR BT.709"\n        val hfrCadence = if (fps >= CaptureModeStore.FPS_120) HighFpsCadenceValidator.inspect(finalFile, fps) else null\n        if (profile != null && hfrCadence != null) {\n            if (hfrCadence.stable) {\n                CaptureStateStore.rememberValidatedModeForFps(\n                    this, resolutionValue(profile.videoSize), sizeName(profile.videoSize), fps\n                )\n            } else {\n                CaptureStateStore.clearEffectiveModeHistoryForFps(this, fps)\n                AppLogRepository.warn(\n                    this, "hfr_cadence",\n                    "${sizeName(profile.videoSize)} $fps FPS entregou ${hfrCadence.label} FPS reais; gaps=${hfrCadence.largeGapRatio}; bursts=${hfrCadence.shortBurstRatio}"\n                )\n            }\n        }\n        // Uma falha estrutural HFR nao deve ser mascarada sintetizando metade do video.\n        if (hfrCadence?.stable != false) AutoGapRepairService.enqueue(this, finalFile, fps)\n        val cadenceLabel = when {\n            hfrCadence == null -> ""\n            hfrCadence.stable -> " • ${hfrCadence.label} FPS reais confirmados"\n            else -> " • ${hfrCadence.label} FPS reais • cadência high-speed instável"\n        }\n        val message = "Vídeo salvo no cofre • ${sizeName(size)} • $fps FPS • $qualityLabel$cadenceLabel • ${formatDuration(durationSeconds)}"''')

activity = 'app/src/main/java/com/steadyvault/camera/ui/capture/CaptureActivity.kt'
replace_once(activity, '''    private val thumbnailExecutor = Executors.newSingleThreadExecutor { task ->\n        Thread({\n            runCatching { Process.setThreadPriority(Process.THREAD_PRIORITY_BACKGROUND) }\n            task.run()\n        }, "SteadyVault-CaptureThumbnail")\n    }''', '''    private val thumbnailExecutor = Executors.newSingleThreadExecutor { task ->\n        Thread({\n            runCatching { Process.setThreadPriority(Process.THREAD_PRIORITY_BACKGROUND) }\n            task.run()\n        }, "SteadyVault-CaptureThumbnail")\n    }\n    private val capabilityExecutor = Executors.newSingleThreadExecutor { task ->\n        Thread({\n            runCatching { Process.setThreadPriority(Process.THREAD_PRIORITY_BACKGROUND) }\n            task.run()\n        }, "SteadyVault-CapabilityScan")\n    }''')
replace_once(activity, '''        idlePreview.release()\n        thumbnailExecutor.shutdownNow()\n        super.onDestroy()''', '''        idlePreview.release()\n        thumbnailExecutor.shutdownNow()\n        capabilityExecutor.shutdownNow()\n        super.onDestroy()''')
old_refresh = '''    private fun refreshCapabilityMatrix(force: Boolean = false) {\n        capabilityMatrix = CaptureCapabilityMatrix.cached(this) ?: capabilityMatrix\n        capabilityScanInProgress = false\n        capabilityRescanPending = false\n        capabilityScanCompleted = true\n        cameraOptions = CameraLensCatalog.options(this).filter { it.isFront || it.logical }\n        synchronizeSelectedCameraWithCatalog()\n        capabilityMatrix?.let { matrix ->\n            val rearCameraIds = cameraOptions.filter { it.isBack }.mapTo(mutableSetOf()) { it.id }\n            val rearMatrix = matrix.copy(\n                modes = matrix.modes.filter { it.cameraId in rearCameraIds },\n                cameras = matrix.cameras.filter { it.cameraId in rearCameraIds }\n            )\n            if (rearMatrix.modes.isNotEmpty()) CaptureModeCatalog.remember(this, rearMatrix)\n        }\n        synchronizeSelectedModeWithCapabilities()\n        alignStoredModeMessage()\n        renderRecordingMode(busy = CaptureStateStore.isBusy(this))\n        renderPreviewQuickControls()\n        renderPreviewSettingsSheetContent()\n    }'''
new_refresh = '''    private fun refreshCapabilityMatrix(force: Boolean = false) {\n        if (capabilityScanInProgress) {\n            if (force) capabilityRescanPending = true\n            return\n        }\n        if (CaptureStateStore.isBusy(this) || photoBusy) {\n            capabilityRescanPending = true\n            return\n        }\n        val cached = if (force) null else CaptureCapabilityMatrix.cached(this)\n        if (cached != null) {\n            applyCapabilityMatrix(cached)\n            return\n        }\n        capabilityScanInProgress = true\n        capabilityScanCompleted = false\n        capabilityRescanPending = false\n        lastCapabilityScanStartedAtMs = SystemClock.elapsedRealtime()\n        renderRecordingMode(busy = false)\n        renderPreviewQuickControls()\n        runCatching {\n            capabilityExecutor.execute {\n                val result = runCatching { CaptureCapabilityMatrix.scan(applicationContext, force = force) }\n                mainHandler.post {\n                    if (isFinishing || isDestroyed) return@post\n                    capabilityScanInProgress = false\n                    capabilityScanCompleted = true\n                    result.onSuccess(::applyCapabilityMatrix)\n                        .onFailure { applyCapabilityMatrix(CaptureCapabilityMatrix.cached(this) ?: capabilityMatrix) }\n                    if (capabilityRescanPending && !CaptureStateStore.isBusy(this) && !photoBusy) {\n                        capabilityRescanPending = false\n                        mainHandler.post { refreshCapabilityMatrix(force = force) }\n                    }\n                }\n            }\n        }.onFailure {\n            capabilityScanInProgress = false\n            capabilityScanCompleted = true\n            applyCapabilityMatrix(CaptureCapabilityMatrix.cached(this) ?: capabilityMatrix)\n        }\n    }\n\n    private fun applyCapabilityMatrix(matrix: CaptureCapabilityMatrix.Matrix?) {\n        capabilityMatrix = matrix ?: capabilityMatrix\n        cameraOptions = CameraLensCatalog.options(this).filter { it.isFront || it.logical }\n        synchronizeSelectedCameraWithCatalog()\n        capabilityMatrix?.let { detected ->\n            val rearCameraIds = cameraOptions.filter { it.isBack }.mapTo(mutableSetOf()) { it.id }\n            val rearMatrix = detected.copy(\n                modes = detected.modes.filter { it.cameraId in rearCameraIds },\n                cameras = detected.cameras.filter { it.cameraId in rearCameraIds }\n            )\n            if (rearMatrix.modes.isNotEmpty()) CaptureModeCatalog.remember(this, rearMatrix)\n        }\n        synchronizeSelectedModeWithCapabilities()\n        alignStoredModeMessage()\n        renderRecordingMode(busy = CaptureStateStore.isBusy(this))\n        renderPreviewQuickControls()\n        renderPreviewSettingsSheetContent()\n    }'''
replace_once(activity, old_refresh, new_refresh)

matrix = 'app/src/main/java/com/steadyvault/camera/core/capability/CaptureCapabilityMatrix.kt'
replace_once(matrix, 'private const val CACHE_SCHEMA = 8', 'private const val CACHE_SCHEMA = 9')

queue = 'app/src/main/java/com/steadyvault/camera/processing/auto/AutoGapRepairQueueStore.kt'
replace_once(queue, '''        val attempts: Int,\n        val message: String,''', '''        val attempts: Int,\n        val progress: Int,\n        val message: String,''')
replace_once(queue, '''            attempts = 0,\n            message = "Aguardando reparo de cadência",''', '''            attempts = 0,\n            progress = 0,\n            message = "Aguardando reparo de cadência",''')
replace_once(queue, '''            attempts = it.attempts + 1,\n            message = message,''', '''            attempts = it.attempts + 1,\n            progress = 0,\n            message = message,''')
replace_once(queue, '''            status = Status.PENDING,\n            message = message,''', '''            status = Status.PENDING,\n            progress = 0,\n            message = message,''')
replace_once(queue, '''            status = Status.SUCCESS,\n            message = message,''', '''            status = Status.SUCCESS,\n            progress = 100,\n            message = message,''')
replace_once(queue, '''            status = Status.SKIPPED,\n            message = message,''', '''            status = Status.SKIPPED,\n            progress = 100,\n            message = message,''')
replace_once(queue, '''            status = Status.ERROR,\n            message = "Falha no reparo automático",''', '''            status = Status.ERROR,\n            progress = 0,\n            message = "Falha no reparo automático",''')
replace_once(queue, '''                    status = Status.PENDING,\n                    message = "Reparo interrompido; será retomado do original",''', '''                    status = Status.PENDING,\n                    progress = 0,\n                    message = "Reparo interrompido; será retomado do original",''')
replace_once(queue, '''                    status = Status.PENDING,\n                    message = "Reparo reenfileirado manualmente",''', '''                    status = Status.PENDING,\n                    progress = 0,\n                    message = "Reparo reenfileirado manualmente",''')
replace_once(queue, '''    @Synchronized\n    fun hasPending(context: Context): Boolean = load(context).any { it.status == Status.PENDING }''', '''    @Synchronized\n    fun updateProgress(context: Context, id: String, progress: Int, message: String): Job? = update(context, id) {\n        it.copy(status = Status.RUNNING, progress = progress.coerceIn(0, 100), message = message, updatedAtMs = System.currentTimeMillis())\n    }\n\n    @Synchronized\n    fun runningJob(context: Context): Job? = load(context)\n        .filter { it.status == Status.RUNNING }\n        .maxByOrNull { it.updatedAtMs }\n\n    @Synchronized\n    fun hasPending(context: Context): Boolean = load(context).any { it.status == Status.PENDING }''')
replace_once(queue, '''        .put("attempts", job.attempts)\n        .put("message", job.message)''', '''        .put("attempts", job.attempts)\n        .put("progress", job.progress)\n        .put("message", job.message)''')
replace_once(queue, '''        attempts = json.optInt("attempts", 0).coerceAtLeast(0),\n        message = json.optString("message", ""),''', '''        attempts = json.optInt("attempts", 0).coerceAtLeast(0),\n        progress = json.optInt("progress", 0).coerceIn(0, 100),\n        message = json.optString("message", ""),''')

auto = 'app/src/main/java/com/steadyvault/camera/processing/auto/AutoGapRepairService.kt'
replace_once(auto, '''    @Volatile private var currentJobId: String? = null\n    @Volatile private var currentProgress = 0''', '''    @Volatile private var currentJobId: String? = null\n    @Volatile private var currentSourcePath: String? = null\n    @Volatile private var currentProgress = 0\n    @Volatile private var currentMessage = ""''')
replace_once(auto, '''                currentJobId = job.id\n                currentProgress = 0''', '''                currentJobId = job.id\n                currentSourcePath = job.sourcePath\n                currentProgress = 0\n                currentMessage = "Preparando reparo automático"''')
replace_once(auto, '''                val continueQueue = processJob(job)\n                currentJobId = null''', '''                val continueQueue = processJob(job)\n                broadcastProgress(running = false)\n                currentJobId = null\n                currentSourcePath = null''')
replace_once(auto, '''    private fun publish(progress: Int, message: String) {\n        currentProgress = progress.coerceIn(0, 100)\n        getSystemService(NotificationManager::class.java)\n            .notify(NOTIFICATION_ID, buildNotification(currentProgress, message))\n    }''', '''    private fun publish(progress: Int, message: String) {\n        currentProgress = progress.coerceIn(0, 100)\n        currentMessage = message\n        currentJobId?.let { AutoGapRepairQueueStore.updateProgress(this, it, currentProgress, message) }\n        broadcastProgress(running = currentProgress < 100)\n        getSystemService(NotificationManager::class.java)\n            .notify(NOTIFICATION_ID, buildNotification(currentProgress, message))\n    }\n\n    private fun broadcastProgress(running: Boolean) {\n        sendBroadcast(Intent(ACTION_STATE).setPackage(packageName).apply {\n            putExtra(EXTRA_SOURCE_PATH, currentSourcePath.orEmpty())\n            putExtra(EXTRA_PROGRESS, currentProgress)\n            putExtra(EXTRA_MESSAGE, currentMessage)\n            putExtra(EXTRA_RUNNING, running)\n        })\n    }''')
replace_once(auto, '''    companion object {\n        private const val ACTION_ENQUEUE = "com.steadyvault.camera.AUTO_GAP_REPAIR_ENQUEUE"''', '''    companion object {\n        const val ACTION_STATE = "com.steadyvault.camera.AUTO_GAP_REPAIR_STATE"\n        const val EXTRA_PROGRESS = "progress"\n        const val EXTRA_MESSAGE = "message"\n        const val EXTRA_RUNNING = "running"\n        private const val ACTION_ENQUEUE = "com.steadyvault.camera.AUTO_GAP_REPAIR_ENQUEUE"''')
replace_once(auto, '''        private const val EXTRA_SOURCE_PATH = "source_path"''', '''        const val EXTRA_SOURCE_PATH = "source_path"''')

manual = 'app/src/main/java/com/steadyvault/camera/processing/service/VideoOptimizationService.kt'
replace_once(manual, '''            putExtra(EXTRA_STATE, state)\n            putExtra(EXTRA_MESSAGE, message)\n            putExtra(EXTRA_PROGRESS, progress)''', '''            putExtra(EXTRA_STATE, state)\n            putExtra(EXTRA_SOURCE_PATH, currentSourcePath.orEmpty())\n            putExtra(EXTRA_MESSAGE, message)\n            putExtra(EXTRA_PROGRESS, progress)''')

vault = 'app/src/main/java/com/steadyvault/camera/ui/vault/PrimaryVaultActivity.kt'
replace_once(vault, '''import com.steadyvault.camera.processing.service.VideoOptimizationService''', '''import com.steadyvault.camera.processing.service.VideoOptimizationService\nimport com.steadyvault.camera.processing.auto.AutoGapRepairService\nimport com.steadyvault.camera.processing.auto.AutoGapRepairQueueStore''')
replace_once(vault, '''    private val optimizationRefresh = object : Runnable {\n        override fun run() {\n            if (!PrimaryVaultLock.isUnlocked(this@PrimaryVaultActivity)) return\n            val snapshot = OptimizationStateStore.snapshot(this@PrimaryVaultActivity)\n            updateOptimizationUi(snapshot)\n            if (snapshot.running) mainHandler.postDelayed(this, OPTIMIZATION_REFRESH_MS) else refresh()\n        }\n    }''', '''    private val optimizationRefresh = object : Runnable {\n        override fun run() {\n            if (!PrimaryVaultLock.isUnlocked(this@PrimaryVaultActivity)) return\n            val snapshot = OptimizationStateStore.snapshot(this@PrimaryVaultActivity)\n            val autoJob = AutoGapRepairQueueStore.runningJob(this@PrimaryVaultActivity)\n            when {\n                snapshot.running -> updateOptimizationUi(snapshot)\n                autoJob != null -> updateProcessingUi(autoJob.sourcePath, autoJob.progress, autoJob.message, "Reparo")\n                else -> { refresh(); return }\n            }\n            mainHandler.postDelayed(this, OPTIMIZATION_REFRESH_MS)\n        }\n    }''')
replace_once(vault, '''    private val optimizationReceiver = object : BroadcastReceiver() {\n        override fun onReceive(context: Context?, intent: Intent?) {\n            val state = intent?.getStringExtra(VideoOptimizationService.EXTRA_STATE).orEmpty()\n            if (state == VideoOptimizationService.STATE_PROGRESS) {\n                updateOptimizationUi(OptimizationStateStore.snapshot(this@PrimaryVaultActivity))\n                scheduleOptimizationRefresh()\n            } else refresh()\n        }\n    }''', '''    private val optimizationReceiver = object : BroadcastReceiver() {\n        override fun onReceive(context: Context?, intent: Intent?) {\n            when (intent?.action) {\n                VideoOptimizationService.ACTION_STATE -> {\n                    val state = intent.getStringExtra(VideoOptimizationService.EXTRA_STATE).orEmpty()\n                    if (state == VideoOptimizationService.STATE_PROGRESS) {\n                        updateProcessingUi(\n                            intent.getStringExtra(VideoOptimizationService.EXTRA_SOURCE_PATH),\n                            intent.getIntExtra(VideoOptimizationService.EXTRA_PROGRESS, 0),\n                            intent.getStringExtra(VideoOptimizationService.EXTRA_MESSAGE).orEmpty(),\n                            "Otimização"\n                        )\n                        scheduleOptimizationRefresh()\n                    } else mainHandler.postDelayed({ refresh() }, 100L)\n                }\n                AutoGapRepairService.ACTION_STATE -> {\n                    val running = intent.getBooleanExtra(AutoGapRepairService.EXTRA_RUNNING, false)\n                    if (running) {\n                        updateProcessingUi(\n                            intent.getStringExtra(AutoGapRepairService.EXTRA_SOURCE_PATH),\n                            intent.getIntExtra(AutoGapRepairService.EXTRA_PROGRESS, 0),\n                            intent.getStringExtra(AutoGapRepairService.EXTRA_MESSAGE).orEmpty(),\n                            "Reparo"\n                        )\n                        scheduleOptimizationRefresh()\n                    } else mainHandler.postDelayed({ refresh() }, 100L)\n                }\n            }\n        }\n    }''')
replace_once(vault, '''        applyGalleryView(page.optimization)\n        if (restorePosition >= 0 && mediaGrid.visibility == View.VISIBLE) {''', '''        applyGalleryView(page.optimization)\n        val autoJob = if (!page.optimization.running) AutoGapRepairQueueStore.runningJob(this) else null\n        if (autoJob != null) adapter.updateProcessing(autoJob.sourcePath, autoJob.progress)\n        if (restorePosition >= 0 && mediaGrid.visibility == View.VISIBLE) {''')
replace_once(vault, '''        storageText.text = if (page.optimization.running) {\n            "Otimização ${page.optimization.progress}% • ${page.optimization.message}"\n        } else {\n            "${page.total} mídia(s) • ${VaultRepository.formatBytes(page.usedBytes)} • privado até exportar"\n        }''', '''        storageText.text = when {\n            page.optimization.running -> "Otimização ${page.optimization.progress}% • ${page.optimization.message}"\n            autoJob != null -> "Reparo ${autoJob.progress}% • ${autoJob.message}"\n            else -> "${page.total} mídia(s) • ${VaultRepository.formatBytes(page.usedBytes)} • privado até exportar"\n        }''')
replace_once(vault, '''    private fun updateOptimizationUi(snapshot: OptimizationStateStore.Snapshot) {\n        if (!::adapter.isInitialized || !::mediaGrid.isInitialized) return\n        val firstPosition = mediaGrid.firstVisiblePosition\n        val firstTop = mediaGrid.getChildAt(0)?.top ?: 0\n        adapter.updateProcessing(snapshot.sourcePath.takeIf { snapshot.running }, snapshot.progress)\n        if (firstPosition >= 0) mediaGrid.setSelectionFromTop(firstPosition, firstTop)\n        if (snapshot.running) storageText.text = "Otimização ${snapshot.progress}% • ${snapshot.message}"\n    }''', '''    private fun updateOptimizationUi(snapshot: OptimizationStateStore.Snapshot) {\n        updateProcessingUi(snapshot.sourcePath.takeIf { snapshot.running }, snapshot.progress, snapshot.message, "Otimização")\n    }\n\n    private fun updateProcessingUi(sourcePath: String?, progress: Int, message: String, label: String) {\n        if (!::adapter.isInitialized || !::mediaGrid.isInitialized) return\n        val firstPosition = mediaGrid.firstVisiblePosition\n        val firstTop = mediaGrid.getChildAt(0)?.top ?: 0\n        adapter.updateProcessing(sourcePath?.takeIf { it.isNotBlank() }, progress)\n        if (firstPosition >= 0) mediaGrid.setSelectionFromTop(firstPosition, firstTop)\n        if (!sourcePath.isNullOrBlank()) storageText.text = "$label ${progress.coerceIn(0, 100)}% • ${message.ifBlank { "Processando vídeo" }}"\n    }''')
replace_once(vault, '''                "Abrir com segurança", "Detalhes", "Ver progresso (${optimization?.progress ?: 0}%)",''', '''                "Abrir original", "Detalhes", "Ver progresso (${optimization?.progress ?: 0}%)",''')
replace_once(vault, '''        val filter = IntentFilter(VideoOptimizationService.ACTION_STATE)''', '''        val filter = IntentFilter().apply {\n            addAction(VideoOptimizationService.ACTION_STATE)\n            addAction(AutoGapRepairService.ACTION_STATE)\n        }''')
replace_once(vault, '''        if (OptimizationStateStore.snapshot(this).running) {\n            mainHandler.postDelayed(optimizationRefresh, OPTIMIZATION_REFRESH_MS)\n        }''', '''        if (OptimizationStateStore.snapshot(this).running || AutoGapRepairQueueStore.runningJob(this) != null) {\n            mainHandler.postDelayed(optimizationRefresh, OPTIMIZATION_REFRESH_MS)\n        }''')
replace_once(vault, '''            holder.processing.text = if (processing) "${if (processingPath == path) processingProgress else 0}%" else ""''', '''            holder.processing.text = if (processing) {\n                if (processingPath == path) "Original • $processingProgress%" else "Original • processando"\n            } else ""''')
replace_once(vault, 'private const val OPTIMIZATION_REFRESH_MS = 1_000L', 'private const val OPTIMIZATION_REFRESH_MS = 350L')

opt_activity = 'app/src/main/java/com/steadyvault/camera/ui/vault/VideoOptimizationActivity.kt'
replace_once(opt_activity, '''        FrameRepairMode.FILL_MISSING_FRAMES,\n        FrameRepairMode.ADAPTIVE_BLEND\n    )''', '''        FrameRepairMode.FILL_MISSING_FRAMES,\n        FrameRepairMode.ADAPTIVE_BLEND,\n        FrameRepairMode.MOTION_COMPENSATED\n    )''')
replace_once(opt_activity, '''                "Preencher lacunas repetindo o quadro mais próximo",\n                "Suavizar lacunas misturando quadros (pode criar rastro)"\n            )''', '''                "Preencher lacunas repetindo o quadro mais próximo",\n                "Suavizar lacunas misturando quadros (pode criar rastro)",\n                "Interpolar lacunas acompanhando o movimento (recomendado)"\n            )''')

print('patch aplicado')
