#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${TMPDIR:-/tmp}/steadyvault-pure-tests"
rm -rf "$OUT"
mkdir -p "$OUT"
FILES=(
  "$ROOT/app/src/main/java/com/steadyvault/camera/capture/timing/RecordingStabilizationPolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/capture/timing/StrictCaptureModePolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/capture/timing/CaptureCadencePolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/capture/timing/SensorCadencePolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/core/camera/OisSupportPolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/core/capability/HardwareSupportPolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/gesture/PlaybackHealthPolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/gesture/PlaybackRecoveryPolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/gesture/LatestScrubTargetQueue.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/gesture/ScrubFramePolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/gesture/ScrubSeekPolicy.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/security/PinLayoutRules.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/vault/VaultGridRules.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/storage/vault/VaultAreaId.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/vault/VaultImportSession.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/ui/vault/VaultImportSummary.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/core/validation/UiBehaviorRules.kt"
  "$ROOT/app/src/main/java/com/steadyvault/camera/photo/quality/PhotoQualityPolicy.kt"
  "$ROOT/tools/PureLogicSmokeTest.kt"
)
kotlinc "${FILES[@]}" -Werror -include-runtime -d "$OUT/tests.jar"
java -jar "$OUT/tests.jar"
